CREATE TABLE users
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(100)            NOT NULL,
    email            VARCHAR(100)            NOT NULL,
    password         VARCHAR(100)            NOT NULL,
    registered       TIMESTAMP DEFAULT now() NOT NULL,
    enabled          BOOLEAN   DEFAULT TRUE  NOT NULL
);

INSERT INTO users(name, email, password) VALUES ('Tom', 'tom@mail.ru', 'tom_password');
INSERT INTO users(name, email, password) VALUES ('Kate', 'kate@mail.ru', 'kate_password');
INSERT INTO users(name, email, password) VALUES ('Bob', 'bob@mail.ru', 'bob_password');